### PR TITLE
 PostgreSql upper case support for all type of db objects.

### PR DESCRIPTION
**Pull request by denizzengin**
Postgre sql upper case support for all type of db objects.
 issue : #226

### CODE REVIEW

**Review by frankhommers — CHANGES_REQUESTED** [review]
The schema name is already configurable, so that doesn't need the GetProperDbName().

**Comment by frankhommers** [comment]
I am not sure if we want it this way. Couldn't we just make all table and column names configurable?

That would also become easier to read I think.

So that we have a class which has something like.
Tables.Job.Name = "job"
Tables.Job.Columns.Id = "id"

What do you think @vytautask and @azygis ? (That would be better than only uppercasing, don't you think?)

**Comment by azygis** [comment]
Indeed. All-uppercase seems to benefit only a small subset of people as I personally haven't seen uppercase object names so far in years. If we are to make it configurable, I'd rather have it configurable "fully".

Naming the method "get *proper* object name" seems a bit harsh. To me proper in postgres is lowercase, to others it can be snake_case, etc.

No statics should be there, instead register table options like any other options in asp.net so these can be injected. Having a static class is generally not a good idea since it's quite easy to accidentally break it.

**Comment by denizzengin** [comment]
Thanks for your replies,
I understand that this option doesn't make big impact general use because of past experience and further lower case  uses strongly enough so that I decided close this pr. My schema in postgre only hangfire specific tables will be lower case I think it isn't a problem.

**Pull request closed without merging**
