### PR TITLE
Should fix #93 issue with multiple transactions. Needs testing though

### LINKED ISSUE #93: BackgroundJob.Enqueue not work in TransactionScope
Using BackgroundJob.Enqueue inside TransactionScope throw exception „System.NotSupportedException: Nested/Concurrent transactions aren't supported.“
The reason is that Npgsql not supports Nested/Concurrent transactions.
Problem is in the method Hangfire.PostgreSql.WriteOnlyTransaction.Commit.
This method always beginning a new sql transaction.
The solution may be beginning new sql transaction only if Transaction.Current is null.

Or, do exists other solution for this problem?

Note:
I tested on the forked project ahydrax/Hangfire.PostgreSql.

### PR DESCRIPTION
**Pull request by vytautask**
Tests should be provided

### CODE REVIEW

**Comment by davidroth** [comment]
@vytautask @frankhommers This MR can be closed now.

**Comment by frankhommers** [comment]
Superseded by davidroth's solution ;-)

**Comment by renriquez-mdsol** [comment]
Just to be sure, it is superseded by: https://github.com/frankhommers/Hangfire.PostgreSql/pull/137
correct?

**Comment by davidroth** [comment]
Yes.

**Pull request closed without merging**
