### PR TITLE
Compatibility with new Npgsql

### PR DESCRIPTION
**Pull request by vytautask**
Compatibility with new Npgsql and stuff. Tried to remove all references to my Revised version but not sure if my attempts were a success :)

### CODE REVIEW

**Comment by bherila** [comment]
Hey @vytautask can you rebase your branch against the latest master? @frankhommers has just merged a couple of other pending pull requests. Thank you both for keeping this project alive!!

Regards,
Ben

**Comment by bherila** [comment]
Also @vytautask please let me know if you need help with rebasing.

Thanks,
Ben

**Comment by vytautask** [comment]
I hope I did well :)

**Comment by bherila** [comment]
Looks good to me @vytautask thanks 👍

**Pull request merged**
