### PR TITLE
Added target 'netcoreapp1.0' to the NuGet package

### PR DESCRIPTION
**Pull request by jenyayel**

### CODE REVIEW

**Comment by jenyayel** [comment]
This should close #54

**Comment by adamhathcock** [comment]
You shouldn't need a separate nuspec anymore.

The relevant info can just be placed in project.json then run `dotnet pack` on it to create the nupkg.

**Comment by jenyayel** [comment]
This will be challenging in this repository - there are 2 separate projects each targets different framework, there is already psake script in place which uses `nuget.exe pack` and nuspec. Also, as you may know, `project.json` won't stay long with us, so I don't see a point changing build automation to `project.json` and in a few month being forced to move to `.csproj`.

**Comment by adamhathcock** [comment]
One mostly reuses the other.  

'project.json' will be converted to the new csproj which will support everything just in XML instead.  I think it's more about consolidating to a single package.  I think going from project.json to new csproj will be easy as it's the same tools/commands under 'dotnet pack'

**Pull request merged**
