### PR TITLE
Fix KeyNotFoundException

### PR DESCRIPTION
**Pull request by bymyslf**
Fixes issues such as https://github.com/frankhommers/Hangfire.PostgreSql/issues/79

### CODE REVIEW

**Comment by vytautask** [comment]
It would be nice to also have tests for this...
If you would not provide those, I'll create them myself in a few upcoming days.

**Comment by bymyslf** [comment]
Yes, I'll do. I was facing this problem yesterday, so I immediately made the fix and created this PR.  At least until the next weekend I'll write the tests. If for some reason I cannot do it, I let you know.

**Comment by bymyslf** [comment]
@vytautask, I've added a bug specific test. If you want more tests for the monitoring API or one test per casing instead of mixing in the same test, let me know or feel free to add more tests.

**Comment by vytautask** [comment]
Released with 1.4.8.2 version 🎉 
Thank you for your contribution! I appreciate it 👍

**Pull request merged**
