### PR TITLE
Bugfix/198.duplicate key value

### PR DESCRIPTION
**Pull request by Frazi1**
Fix for #198

### CODE REVIEW

**Comment by vytautask** [comment]
Thanks!
AppVeyor tests seem to fail after merge.

**Comment by Frazi1** [comment]
What exactly is failing? Can you get me some error messages?

**Comment by vytautask** [comment]
PostgreSqlWriteOnlyTransactionFacts.cs(509,1): error CS8401: To use '@$'
instead of '$@' for an interpolated verbatim string, please use language
version 'preview' or greater.
[C:\projects\hangfire-postgresql-lel5h\tests\Hangfire.PostgreSql.Tests\Hangfire.PostgreSql.Tests.csproj]
PostgreSqlWriteOnlyTransactionFacts.cs(524,1): error CS8401: To use '@$'
instead of '$@' for an interpolated verbatim string, please use language
version 'preview' or greater.
[C:\projects\hangfire-postgresql-lel5h\tests\Hangfire.PostgreSql.Tests\Hangfire.PostgreSql.Tests.csproj]

Geros dienos,
Vytautas Kasparavičius


2021-07-02, pn, 10:23 Dmitri Vychikov ***@***.***> rašė:

**Comment by Frazi1** [comment]
Oh, sorry for that. I'll fix it right away.

**Comment by Frazi1** [comment]
@vytautask Should be fixed by https://github.com/frankhommers/Hangfire.PostgreSql/pull/200

**Comment by Frazi1** [comment]
By the way, have you considered running AppVeyor tests against submitted PRs before you merge to master?

**Comment by vytautask** [comment]
> 
> 
> By the way, have you considered running AppVeyor tests against submitted PRs before you merge to master?

I have, but currently have no time to dig into that.

**Pull request merged**
