### PR TITLE
Change AppVeyor database timezone to non-UTC to surface DateTime conversion issues under test

### PR DESCRIPTION
**Pull request by Plasma**
See https://github.com/frankhommers/Hangfire.PostgreSql/issues/221#issuecomment-1001277778

This PR changes the appveyor CI's test database timezone to be non-UTC, to expose unit test failures due to DateTime timezone conversion issues under Npgsql 6.

__Note__ Unfortunately appveyor is hiding the test failures in the Tests tab, if you see the Console output though you will see failures. This is because the unit tests are run twice (once for Npgsql 6, then 5) so they initially fail but are overridden to pass when the npgql 5 configuration is ran.

I tried duplicating the test results with separate test config files but appveyor did not show the tests twice as desired, ideally we could fix that too to show the combined test results.

### CODE REVIEW

**Comment by frankhommers** [comment]
> See [#221 (comment)](https://github.com/frankhommers/Hangfire.PostgreSql/issues/221#issuecomment-1001277778)
> 
> This PR changes the appveyor CI's test database timezone to be non-UTC, to expose unit test failures due to DateTime timezone conversion issues under Npgsql 6.

> **Note** Unfortunately appveyor is hiding the test failures in the Tests tab, if you see the Console output though you will see failures. This is because the unit tests are run twice (once for Npgsql 6, then 5) so they initially fail but are overridden to pass when the npgql 5 configuration is ran.

This might be something we need to fix anyway, @azygis, ideas? ... since you kind of introduced this? ;)

> I tried duplicating the test results with separate test config files but appveyor did not show the tests twice as desired, ideally we could fix that too to show the combined test results.

Maybe this will be fixed as well when we fix the first one?

**Comment by azygis** [comment]
Well, that's a shame. Azure shows duplicated test runs if one just runs tests multiple times. Apparently appveyor isn't able to do so.

I'll see what I can do, but not sure if I'm able to dig into it this week. Regardless, this is probably not a hard blocker on pull request, is it? Just need to take a look at the logs once in a while. The root fix shouldn't cause any issues, as long as the build succeeds in appveyor logs for both packages.

**Comment by Plasma** [comment]
I’ve emailed appveyor to see if there’s any suggestions, perhaps we need two separate builds for v5 and v6 (if that’s doable with appveyor), will let you know what I hear.

**Comment by Plasma** [comment]
I've updated the `appveyor.yml` to use `matrix builds` (run multiple build jobs with different parameters) and pushed that change to this PR (and separately by itself in PR #233 which shows the tests passing with UTC timezone right now).

You can see the Npgsql v6 tests failing due to the non-UTC timezone change too (this PR) at https://ci.appveyor.com/project/AndrewA/hangfire-postgresql/builds/42029046

Perhaps merge #233 first to setup the separate projects, and this PR demonstrates the CI failures, so perhaps we can determine an appropriate fix for the issue before merging this PR (that will start failing the build).

The easiest solution I think I found so far was just ensuring `Timezone=UTC` was set in the connection string (to discard the default, non-UTC time the server may be configured to use). We could either document this behavior (feels a bit brittle) or just enforce in code by forcing the Timezone parameter to be UTC during connection string parsing.

**Comment by Plasma** [comment]
Introduced PR #234 which incorporates this PR (and #233) with an attempted fix to the non-UTC issue by ensuring the connection timezone is always UTC based (tests pass, see https://ci.appveyor.com/project/AndrewA/hangfire-postgresql/builds/42029218 )

**Comment by Plasma** [comment]
This PR is included in and fixed by #234

**Pull request closed without merging**
