### PR TITLE
Compile with .NET Core

### PR DESCRIPTION
**Pull request by zhongzf**

### CODE REVIEW

**Comment by zhongzf** [comment]
NuGet package:
https://www.nuget.org/packages/Hangfire.PostgreSql.NetCore

**Comment by frankhommers** [comment]
@vytautask to me this PR seems OK, what do you think?

**Comment by vytautask** [comment]
@frankhommers looks good.  Do all tests pass?
+not sure about AssemblyVersionInfo and project.json changes (should there be any?).
I will investigate how other open source projects cope with Core versions and NuGet as I would like to not split it into separate projects...

**Comment by frankhommers** [comment]
@vytautask I didn't test it yet. I thought project.json was deprecated already. Read http://stackoverflow.com/questions/38536978/is-project-json-deprecated (that's for ASP.NET, but I'm unsure if it applies to this project). @zhongzf: What is your opinion on this?

**Comment by zhongzf** [comment]
@frankhommers thanks for the information, yes, heard that before, but I think before the official release, we can just follow what we have now, isn't it?

**Comment by zhongzf** [comment]
@vytautask sorry, for quick use, I just separated to a new project and released with NuGet, but for the official release just use the same project and NuGet package should be fine.

**Comment by alasvant** [comment]
Hi, first sorry if replying to wrong place but my comment is about .Net Core Hangfire using PostgreSQL.

I created a new asp.net core app and added NuGet packages Hangfire 1.6.4 and Hangfire.PostgreSQL.NetCore 1.4.1

Added required configuration and run the app (with trace logging). I can see in the logs:
- Hangfire.PostgreSql.PostgreSqlStorage|INFO|  Start installing Hangfire SQL objects... 
- Hangfire.PostgreSql.PostgreSqlStorage|INFO|  Hangfire SQL objects installed.

So everything should be fine but in reality the DB has not been created.

@zhongzf I think you have forgot to embed the sql scripts to the assembly in your project.json
as looking with ILSpy to the assembly (Hangfire.PostgreSql.NetCore .dll 1.4.1.0) there are no embedded resources. When the https://github.com/zhongzf/Hangfire.PostgreSql.NetCore/blob/master/src/Hangfire.PostgreSql/PostgreSqlObjectsInstaller.cs starts it prints out the first info message and if there is exception of type MissingManifestResourceException it is swallowed and break used to exit the while loop and happily print out "Hangfire SQL objects installed." which isn't true in this case.

@zhongzf could you please have a look at your code and publish a new fixed version of the NuGet, cheers and thanks for the great work :)

**Comment by zhongzf** [comment]
@alasvant thanks a lot for the correction, the new package has been published.
https://www.nuget.org/packages/Hangfire.PostgreSql.NetCore/1.4.2

**Comment by alasvant** [comment]
@zhongzf Hi, still no DB created. I think there is still issue with the resource names. The code uses Hangfire.PostgreSql.Install.v{0}.sql string format, but I think that should be Hangfire.PostgreSql**.NetCore.**Install.v{0}.sql to work.

**Comment by zhongzf** [comment]
@alasvant my fault, didn't find the way to change the default namespace, so I just changed the code accordingly, and published on nuget, please check this time. thanks a lot!
https://www.nuget.org/packages/Hangfire.PostgreSql.NetCore/1.4.3

**Comment by alasvant** [comment]
Hi, I can confirm that the Hangfire.PostgreSql.NetCore v1.4.3 NuGet works now :) Database created and quick tests with some sample calls to BackgroundJob.Enqueue seems to work nicely.

**Comment by zhongzf** [comment]
@alasvant Thank you so much for your helping and confirmation.

**Comment by vytautask** [comment]
The solution was not that simple... Will need additional testing...

**Comment by vytautask** [comment]
One test is failing. 
@alasvant, @zhongzf maybe you could check it out?

**Comment by bherila** [comment]
@vytautask just in case this is missed can you open a new issue with the details of the failed test? I would do it now but i'm mobile and not so easy to find from here :)

**Pull request merged**
