### PR TITLE
Fixed distributed lock connection state

### PR DESCRIPTION
**Pull request by azygis**
Silently swallowing the exception when trying to lock resources is not always a good idea. This PR does add the logging for when the resource actually fails to get locked. Could make it configurable if necessary.

The actual problem which has been hidden by swallowing is that the stale connection can be used when locking the resources. If the connection gets closed (not by the code, but infrastructure/server issues) while executing any of the scripts, all the retries are happening with a closed connection, which of course would never work without explicitly opening it.

### CODE REVIEW

**Comment by vytautask** [comment]
Thanks for your contribution! 🥳 

I feel that this is more or less like a band-aid but let's release this.

**Comment by vytautask** [comment]
Will release with 1.8.4 version.

**Comment by nevaldas** [comment]
> Thanks for your contribution! 🥳
> 
> I feel that this is more or less like a band-aid but let's release this.

Yep, this is a band-aid, but proper implementation would require quite a rewrite. But in short, looking into how Hangfire solved this within SqlServer, they simply create and open a new connection between any action (unless a dedicated db connection was provided). [Here is an example for dequeueing a job](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerJobQueue.cs#L232).

**Comment by cubed-it** [comment]
Swallowing exceptions completely and independently of the content is not a good idea. However, it also doesn't make sense to constantly log a relatively "normal" internal message. We now have hundreds to thousands of such entries per day.

image

**Comment by azygis** [comment]
You can configure your logger and ignore all logs from that source. That way it's back to silent class again.

**Comment by frankhommers** [comment]
Read #119 , should we swallow at a specific state and constraintname in the exception?

**Comment by Frazi1** [comment]
> Read #119 , should we swallow at a specific state and constraintname in the exception?

I'm in favor of using `Debug` or `Trace` log level instead of `Warn`.

Warn indicates system misbehavior. Switching to a lower level will make it more clear to the consumers that it is not a bug, but expected behavior.

Moreover, Debug and Trace levels are very likely to be disabled in the consumer systems, so a lot of people will stop seeing this message. But this approach gives us the opportunity to enable it on demand for troubleshooting purposes.

**Pull request merged**
