### PR TITLE
WIP: Major code style overhaul

### PR DESCRIPTION
**Pull request by frankhommers**
@vytautask You might take a look at this one.

I am modernizing a lot of stuff. Namely code style and also C# 10.

### CODE REVIEW

**Comment by azygis** [comment]
Curious - what moves you to use 2 spaces in C# as opposed to somewhat standard 4 spaces?

**Comment by vytautask** [comment]
This also had me wondering that it’s a good time to introduce .editorconfig to our project ;)

**Comment by frankhommers** [comment]
Tab sizes are a matter of taste IMO. I almost everywhere use 2. I started doing so years back, just after I pushed my first commit to this repo. But couldn't be bothered to fix it here. But now with all the changes, I'd thought I'd take it.

But I wouldn't put the emphasis on tabs/spaces. 

There is a lot more going on like string interpolation and explicit variables.

**Comment by frankhommers** [comment]
@vytautask Do you know what we need to fix for these checks to work again?

**Comment by azygis** [comment]
You need to set appveyor image. Apparently, [by default](https://www.appveyor.com/docs/build-environment/#choosing-image-for-your-builds) appveyor uses vs 2015 image which does not support .net 6. You need VS 2022 image for .net 6.

**Comment by vytautask** [comment]
> @vytautask Do you know what we need to fix for these checks to work again?

I've fixed it on master but seems to somehow not work for this particular branch. Will investigate in the evening.

**Comment by vytautask** [comment]
@frankhommers I would guess that cake should be updated with used framework versions.

**Pull request merged**
