### PR TITLE
1.7.0

### PR DESCRIPTION
**Pull request by vytautask**
Major version upgrade with #145, #140 and major hangfire version upgrade (as well as npgsql).
Now it only targets standard2.0 (mainly because of npgsql upgrade).

### CODE REVIEW

**Comment by ddo88** [comment]
thanks, waiting for this version.

**Comment by jufmejiagu** [comment]
Thanks! This is super helpful 👍

**Comment by iCyberon** [comment]
@vytautask thanks. When do you think this can be released? We're experiencing the issue described in #140.

**Comment by Atrox** [comment]
I've published the `v1.7.0` branch to nuget as-is `dotnet add package Atrox.Hangfire.PostgreSql --version 1.7.0` . Works great for me :) I would also love an official release.

@vytautask is there anything left to do for v1.7.0? I can help if you need a hand.

**Comment by vytautask** [comment]
I'm having second thoughts about removing net451 support. However, that makes perfect sense as .net framework 4.5.1 is now more than 6 years old and folks had enough time to upgrade...

**Comment by vytautask** [comment]
Uploaded package to nuget.org.
Thanks everyone for support!

**Pull request merged**
